services:
  - type: web
    name: controle-financeiro-api
    runtime: node
    plan: free
    buildCommand: pnpm install --no-frozen-lockfile && pnpm --filter @workspace/api-server run build
    startCommand: pnpm --filter @workspace/api-server run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: GMAIL_USER
        sync: false
      - key: GMAIL_APP_PASSWORD
        sync: false

  - type: web
    runtime: static
    name: controle-financeiro-app
    buildCommand: pnpm install --no-frozen-lockfile && export EXPO_PUBLIC_API_URL="https://${API_HOST}/api" && pnpm --filter @workspace/controle-financeiro exec expo export --platform web --output-dir static-build/web
    staticPublishPath: artifacts/controle-financeiro/static-build/web
    envVars:
      - key: API_HOST
        fromService:
          name: controle-financeiro-api
          type: web
          property: host
